# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('url', models.CharField(max_length=4000, null=True)),
                ('show', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('isSeller', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_token',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
